### ISSUE TITLE
It not work on windows 10

### ISSUE THREAD

**Issue by googlb** [codeabovelab/haven-ui#3]
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.10.9
3 info using node@v6.9.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle haven@0.1.0~predev: haven@0.1.0
6 silly lifecycle haven@0.1.0~predev: no script for predev, continuing
7 info lifecycle haven@0.1.0~dev: haven@0.1.0
8 verbose lifecycle haven@0.1.0~dev: unsafe-perm in lifecycle true
10 verbose lifecycle haven@0.1.0~dev: CWD: D:\git\haven-ui
11 silly lifecycle haven@0.1.0~dev: Args: [ '/d /s /c',
11 silly lifecycle   'concurrent --kill-others "npm run watch-client" "npm run start-dev"' ]
12 silly lifecycle haven@0.1.0~dev: Returned: code: 1  signal: null
13 info lifecycle haven@0.1.0~dev: Failed to exec dev script
14 verbose stack Error: haven@0.1.0 dev: `concurrent --kill-others "npm run watch-client" "npm run start-dev"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid haven@0.1.0
16 verbose cwd D:\git\haven-ui
17 error Windows_NT 10.0.14393
18 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.9.2
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error haven@0.1.0 dev: `concurrent --kill-others "npm run watch-client" "npm run start-dev"`
22 error Exit status 1
23 error Failed at the haven@0.1.0 dev script 'concurrent --kill-others "npm run watch-client" "npm run start-dev"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the haven package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     concurrent --kill-others "npm run watch-client" "npm run start-dev"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs haven
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls haven
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mchwang** [comment]
Sorry we currently do not support Windows platform yet.
